# Generated by Django 2.2.5 on 2019-12-25 11:18

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_name', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='客户名称')),
            ],
            options={
                'ordering': ('customer_name',),
            },
        ),
        migrations.CreateModel(
            name='ProjectNumber',
            fields=[
                ('project_number', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='项目号')),
                ('customer_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='technology_lesson_learned.Customer')),
            ],
            options={
                'ordering': ('customer_name', 'project_number'),
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='标题')),
                ('issue', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='问题描述')),
                ('solution', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='解决方案')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_updated_date', models.DateTimeField(auto_now=True, verbose_name='最后修改时间')),
                ('is_delete', models.BooleanField(default=False)),
                ('project_info', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='technology_lesson_learned.ProjectNumber', verbose_name='客户及项目号')),
            ],
            options={
                'ordering': ('-created_date',),
            },
        ),
    ]
